/**
 * gamesCatalog.ts — Catálogo completo dos 50 jogos do Theta Music Trainer
 *
 * Estrutura: cada jogo tem id, nome, emoji, categoria, descrição curta,
 * descrição longa, skills treinadas, se usa microfone, e a mecânica base.
 *
 * Categorias:
 *  - sound:     5 jogos (Channel Scramble, Band Match, EQ Match, Flash Effects, Flash Terms)
 *  - pitch:     4 jogos (Pitch Compare, Speed Pitch, Dango Brothers, Vocal Match)
 *  - rhythm:    5 jogos (Rhythm Puzzles, Flash Rhythms, Rhythm Repeat, Rhythm Reader, Flash Styles Drums)
 *  - tonality:  9 jogos (Tonic Finder, Key Puzzles, Number Blaster, Paddle Tones, Tone Drops,
 *                         Tonal Recall, Vocal Degrees Major/Minor, Flash Tones, Flash Notation Notes)
 *  - melody:   11 jogos (Melodic Drops, Harmonic Drops, Flash Intervals M/H, Two Tones M/m,
 *                         Three Tones M/m, More Tones M/m, Flash Notation Intervals, Parrot Phrases,
 *                         Vocal Steps Repeat)
 *  - harmony:  16 jogos (Chord Drops, Flash Chords, Tone Trees, Phrase Fitter, Speed Chords,
 *                         Flash Chords Quality, Flash Notation Chords, Chord Spells, Chord Locks,
 *                         Speaker Chords, Flash Progressions M/m, Flash Cadences, Triads,
 *                         Seventh Chords, Inversions, Arpeggios, Harmony Singing)
 *
 * Total: 50 jogos
 */

export type GameCategory = "sound" | "pitch" | "rhythm" | "tonality" | "melody" | "harmony";

export type GameMechanic =
  | "multiple-choice"   // ouça X, escolha entre N opções
  | "singing"           // cante via microfone
  | "rhythm-tap"        // bata o ritmo
  | "tuning"            // ajuste fino
  | "puzzle"            // arraste/solte
  | "falling-objects"   // tons caem, identifique
  | "flashcard"         // flash cards (memorize)
  | "sequence-repeat";  // repita a sequência

export interface GameDef {
  id: string;
  name: string;
  emoji: string;
  category: GameCategory;
  shortDescription: string;
  longDescription: string;
  skills: string[];
  uses_mic: boolean;
  mechanic: GameMechanic;
  accent: string; // tailwind gradient
  /** Número de níveis (sempre 20 no Theta, mas alguns têm variações) */
  levels: number;
}

export const CATEGORY_LABELS: Record<GameCategory, string> = {
  sound: "Som",
  pitch: "Pitch",
  rhythm: "Ritmo",
  tonality: "Tonalidade",
  melody: "Melodia",
  harmony: "Harmonia",
};

export const CATEGORY_COLORS: Record<GameCategory, string> = {
  sound: "from-cyan-500 to-blue-600",
  pitch: "from-emerald-500 to-teal-600",
  rhythm: "from-orange-500 to-red-600",
  tonality: "from-indigo-500 to-purple-600",
  melody: "from-pink-500 to-rose-600",
  harmony: "from-amber-500 to-orange-600",
};

export const CATEGORY_EMOJIS: Record<GameCategory, string> = {
  sound: "🔊",
  pitch: "🎵",
  rhythm: "🥁",
  tonality: "🎼",
  melody: "🎶",
  harmony: "🎸",
};

export const GAMES: GameDef[] = [
  // ═══════════════════════════════════════════════════
  // SOUND (5 jogos)
  // ═══════════════════════════════════════════════════
  {
    id: "channel-scramble",
    name: "Channel Scramble",
    emoji: "🎛️",
    category: "sound",
    shortDescription: "Ajuste o volume de cada canal pra mixar a banda.",
    longDescription: "Channel Scramble treina seu ouvido pra mixagem. Você ouve uma faixa com vários instrumentos e precisa ajustar o volume de cada canal (bateria, baixo, guitarra, voz, etc.) até que o mix soe balanceado.",
    skills: ["Mixing", "Frequency balance", "Level matching"],
    uses_mic: false,
    mechanic: "puzzle",
    accent: "from-cyan-500 to-blue-600",
    levels: 20,
  },
  {
    id: "band-match",
    name: "Band Match",
    emoji: "🎸",
    category: "sound",
    shortDescription: "Determine quais instrumentos estão tocando juntos.",
    longDescription: "Band Match treina seu ouvido pra identificar instrumentos individuais numa mix. Você ouve um trecho e precisa dizer quais instrumentos estão presentes.",
    skills: ["Instrument ID", "Timbre recognition", "Audio isolation"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-cyan-500 to-blue-600",
    levels: 20,
  },
  {
    id: "eq-match",
    name: "EQ Match",
    emoji: "🎚️",
    category: "sound",
    shortDescription: "Ajuste equalizador pra match com o som alvo.",
    longDescription: "EQ Match treina seu ouvido pra identificar mudanças de EQ. Você ouve um som alvo e ajusta bands de EQ até match.",
    skills: ["EQ", "Frequency recognition", "Spectral hearing"],
    uses_mic: false,
    mechanic: "puzzle",
    accent: "from-cyan-500 to-blue-600",
    levels: 20,
  },
  {
    id: "flash-effects",
    name: "Flash Effects",
    emoji: "✨",
    category: "sound",
    shortDescription: "Reconheça efeitos: delay, chorus, compression, etc.",
    longDescription: "Flash Effects treina reconhecimento de efeitos de áudio. Ouça um som e identifique qual efeito foi aplicado.",
    skills: ["Effects", "Delay", "Chorus", "Reverb", "Compression"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-cyan-500 to-blue-600",
    levels: 20,
  },
  {
    id: "flash-terms-performance",
    name: "Flash Terms (Performance)",
    emoji: "📝",
    category: "sound",
    shortDescription: "Memorize termos de performance musical.",
    longDescription: "Flash Terms treina vocabulário de performance. Memoria termos como crescendo, ritardando, staccato, etc.",
    skills: ["Vocabulary", "Performance terms", "Italian terms"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-cyan-500 to-blue-600",
    levels: 20,
  },

  // ═══════════════════════════════════════════════════
  // PITCH (4 jogos)
  // ═══════════════════════════════════════════════════
  {
    id: "pitch-compare",
    name: "Pitch Compare",
    emoji: "⚖️",
    category: "pitch",
    shortDescription: "Compare dois tons em instrumentos diferentes.",
    longDescription: "Pitch Compare é um jogo de ear training: ouça dois tons (em instrumentos diferentes) e diga se o segundo é mais alto, mais baixo ou igual.",
    skills: ["Pitch discrimination", "Relative pitch"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-emerald-500 to-teal-600",
    levels: 20,
  },
  {
    id: "speed-pitch",
    name: "Speed Pitch",
    emoji: "⚡",
    category: "pitch",
    shortDescription: "Compare tons rapidamente (cronometrado).",
    longDescription: "Speed Pitch é Pitch Compare cronometrado. Resposta rápida + correta = mais pontos. Velocidade crescente.",
    skills: ["Quick pitch compare", "Reaction time"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-emerald-500 to-teal-600",
    levels: 20,
  },
  {
    id: "dango-brothers",
    name: "Dango Brothers",
    emoji: "🍡",
    category: "pitch",
    shortDescription: "Detecte a diferença fina entre 2 tons (cents).",
    longDescription: "Dango Brothers afia seu ouvido pra micro-diferenças de pitch (cents). Diferenças começam grandes e diminuem até poucos cents.",
    skills: ["Fine pitch", "Tuning", "Cents discrimination"],
    uses_mic: false,
    mechanic: "tuning",
    accent: "from-emerald-500 to-teal-600",
    levels: 20,
  },
  {
    id: "vocal-match",
    name: "Vocal Match",
    emoji: "🎤",
    category: "pitch",
    shortDescription: "Cante a frase melódica que ouvir.",
    longDescription: "Vocal Match é o jogo principal de canto. Ouça uma frase melódica e cante de volta. 20 níveis: nota isolada → acordes completos.",
    skills: ["Pitch matching", "Melodic memory", "Sight singing"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-emerald-500 to-teal-600",
    levels: 20,
  },

  // ═══════════════════════════════════════════════════
  // RHYTHM (5 jogos)
  // ═══════════════════════════════════════════════════
  {
    id: "rhythm-puzzles",
    name: "Rhythm Puzzles",
    emoji: "🧩",
    category: "rhythm",
    shortDescription: "Identifique padrões rítmicos por ouvido.",
    longDescription: "Rhythm Puzzles: ouça um padrão rítmico e encaixe as peças (notas) pra formar a notação correta.",
    skills: ["Rhythm ID", "Notation", "Time signatures"],
    uses_mic: false,
    mechanic: "puzzle",
    accent: "from-orange-500 to-red-600",
    levels: 20,
  },
  {
    id: "flash-rhythms",
    name: "Flash Rhythms",
    emoji: "🎺",
    category: "rhythm",
    shortDescription: "Match o ritmo que ouvir com sua notação.",
    longDescription: "Flash Rhythms: ouça um ritmo e escolha a notação correta entre 4 opções.",
    skills: ["Rhythm reading", "Pattern matching"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-orange-500 to-red-600",
    levels: 20,
  },
  {
    id: "rhythm-repeat",
    name: "Rhythm Repeat",
    emoji: "🥁",
    category: "rhythm",
    shortDescription: "Bata o ritmo que ouviu (teclado/mouse).",
    longDescription: "Rhythm Repeat: ouça um padrão rítmico e bata de volta usando teclado ou mouse. Treina timing e memória rítmica.",
    skills: ["Rhythm memory", "Timing", "Performance"],
    uses_mic: false,
    mechanic: "rhythm-tap",
    accent: "from-orange-500 to-red-600",
    levels: 20,
  },
  {
    id: "rhythm-reader",
    name: "Rhythm Reader",
    emoji: "📖",
    category: "rhythm",
    shortDescription: "Leia notação rítmica e bata o ritmo.",
    longDescription: "Rhythm Reader: veja a notação rítmica escrita e bata o ritmo correspondente. Sight-reading rítmico.",
    skills: ["Sight reading", "Rhythm notation", "Performance"],
    uses_mic: false,
    mechanic: "rhythm-tap",
    accent: "from-orange-500 to-red-600",
    levels: 20,
  },
  {
    id: "flash-styles-drums",
    name: "Flash Styles (Drums)",
    emoji: "🥁",
    category: "rhythm",
    shortDescription: "Reconheça estilos de bateria (shuffle, ballad, etc).",
    longDescription: "Flash Styles (Drums): ouça um padrão de bateria e identifique o estilo (shuffle, ballad, rock, funk, etc).",
    skills: ["Drum styles", "Genre recognition"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-orange-500 to-red-600",
    levels: 20,
  },

  // ═══════════════════════════════════════════════════
  // TONALITY (9 jogos)
  // ═══════════════════════════════════════════════════
  {
    id: "tonic-finder",
    name: "Tonic Finder",
    emoji: "🎯",
    category: "tonality",
    shortDescription: "Encontre a tônica de uma melodia.",
    longDescription: "Tonic Finder: ouça uma melodia e identifique a nota tônica (a nota que soa como 'casa'). Treina sense of key.",
    skills: ["Tonic ID", "Key recognition", "Tonal center"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "flash-notation-notes",
    name: "Flash Notation (Notes)",
    emoji: "📋",
    category: "tonality",
    shortDescription: "Identifique notas na pauta rapidamente.",
    longDescription: "Flash Notation (Notes): veja uma nota na pauta e identifique seu nome. Sight-reading de notas.",
    skills: ["Sight reading", "Note names", "Staff positions"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "key-puzzles",
    name: "Key Puzzles",
    emoji: "🔑",
    category: "tonality",
    shortDescription: "Aprenda o Círculo das Quintas e tons relativos.",
    longDescription: "Key Puzzles: encaixe as assinaturas de clave no Círculo das Quintas. Ensina relações entre tons maiores e menores.",
    skills: ["Circle of Fifths", "Key signatures", "Relative keys"],
    uses_mic: false,
    mechanic: "puzzle",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "number-blaster",
    name: "Number Blaster",
    emoji: "🔢",
    category: "tonality",
    shortDescription: "Match números com tons e acordes.",
    longDescription: "Number Blaster: ouça um tom/acorde e clique no número do scale degree correspondente. Jogo de queda como Tone Drops.",
    skills: ["Scale degrees", "Numbered notation", "Relative pitch"],
    uses_mic: false,
    mechanic: "falling-objects",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "paddle-tones",
    name: "Paddle Tones",
    emoji: "🏓",
    category: "tonality",
    shortDescription: "Identifique scale tones (estilo Pong).",
    longDescription: "Paddle Tones: tons caem como no Pong. Mova o paddle pro scale degree correto. Treina relative pitch rápido.",
    skills: ["Scale tones", "Quick ID", "Relative pitch"],
    uses_mic: false,
    mechanic: "falling-objects",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "tone-drops",
    name: "Tone Drops",
    emoji: "💧",
    category: "tonality",
    shortDescription: "Identifique scale degree de tons que caem.",
    longDescription: "Tone Drops: tons caem como gotas. Ouça e clique no scale degree (1-7) antes de tocar o chão.",
    skills: ["Scale degrees", "Relative pitch", "Quick ID"],
    uses_mic: false,
    mechanic: "falling-objects",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "tonal-recall",
    name: "Tonal Recall",
    emoji: "🧠",
    category: "tonality",
    shortDescription: "Memorize e recupere tons (jogo de memória).",
    longDescription: "Tonal Recall: jogo da memória com tons. Ouça uma sequência de tons e repita na ordem correta.",
    skills: ["Tonal memory", "Sequence recall", "Pitch memory"],
    uses_mic: false,
    mechanic: "sequence-repeat",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "vocal-degrees-major",
    name: "Vocal Degrees (Major)",
    emoji: "🎼",
    category: "tonality",
    shortDescription: "Cante o scale degree sobre acorde de fundo.",
    longDescription: "Vocal Degrees (Major): ouça um acorde de tônica e cante o scale degree solicitado (1=Tônica, 5=Dominante, etc).",
    skills: ["Scale degrees", "Singing", "Tonal center"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "vocal-degrees-minor",
    name: "Vocal Degrees (Minor)",
    emoji: "🎼",
    category: "tonality",
    shortDescription: "Cante scale degrees em tonalidade menor.",
    longDescription: "Vocal Degrees (Minor): igual ao Major mas em tons menores. Treina internalização da escala menor.",
    skills: ["Minor scale", "Singing", "Scale degrees"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },
  {
    id: "flash-tones",
    name: "Flash Tones",
    emoji: "💡",
    category: "tonality",
    shortDescription: "Identifique scale degrees em diferentes tons.",
    longDescription: "Flash Tones: ouça um tom e identifique rapidamente o scale degree. Vários tons diferentes.",
    skills: ["Scale degrees", "Quick ID", "Multiple keys"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-indigo-500 to-purple-600",
    levels: 20,
  },

  // ═══════════════════════════════════════════════════
  // MELODY (11 jogos)
  // ═══════════════════════════════════════════════════
  {
    id: "melodic-drops",
    name: "Melodic Drops",
    emoji: "🎵",
    category: "melody",
    shortDescription: "Identifique intervalos melódicos.",
    longDescription: "Melodic Drops: ouça um intervalo melódico (2 notas em sequência) e identifique quantos semitons.",
    skills: ["Melodic intervals", "Interval ID"],
    uses_mic: false,
    mechanic: "falling-objects",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "harmonic-drops",
    name: "Harmonic Drops",
    emoji: "🎈",
    category: "melody",
    shortDescription: "Identifique intervalos harmônicos (simultâneos).",
    longDescription: "Harmonic Drops: ouça 2 notas simultâneas (intervalo harmônico) e identifique o intervalo.",
    skills: ["Harmonic intervals", "Interval ID"],
    uses_mic: false,
    mechanic: "falling-objects",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "flash-intervals-melodic",
    name: "Flash Intervals (Melodic)",
    emoji: "⚡",
    category: "melody",
    shortDescription: "Identifique intervalos melódicos rapidamente.",
    longDescription: "Flash Intervals (Melodic): ouça 2 notas em sequência e identifique o intervalo (m2, M3, P5, etc).",
    skills: ["Melodic intervals", "Quick ID"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "flash-intervals-harmonic",
    name: "Flash Intervals (Harmonic)",
    emoji: "⚡",
    category: "melody",
    shortDescription: "Identifique intervalos harmônicos rapidamente.",
    longDescription: "Flash Intervals (Harmonic): ouça 2 notas simultâneas e identifique o intervalo.",
    skills: ["Harmonic intervals", "Quick ID"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "two-tones-major",
    name: "Two Tones (Major)",
    emoji: "②",
    category: "melody",
    shortDescription: "Cante 2 notas (intervalo) em tom maior.",
    longDescription: "Two Tones (Major): ouça 2 notas e cante de volta. Treina memória de intervalos curtos em contexto maior.",
    skills: ["Interval singing", "Major key", "Memory"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "two-tones-minor",
    name: "Two Tones (Minor)",
    emoji: "②",
    category: "melody",
    shortDescription: "Cante 2 notas em tom menor.",
    longDescription: "Two Tones (Minor): igual ao Major mas em tom menor.",
    skills: ["Interval singing", "Minor key", "Memory"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "three-tones-major",
    name: "Three Tones (Major)",
    emoji: "③",
    category: "melody",
    shortDescription: "Cante 3 notas em tom maior.",
    longDescription: "Three Tones (Major): ouça 3 notas e cante de volta. Frases melódicas curtas.",
    skills: ["Melodic memory", "Singing", "Major key"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "three-tones-minor",
    name: "Three Tones (Minor)",
    emoji: "③",
    category: "melody",
    shortDescription: "Cante 3 notas em tom menor.",
    longDescription: "Three Tones (Minor): igual ao Major mas em tom menor.",
    skills: ["Melodic memory", "Singing", "Minor key"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "more-tones-major",
    name: "More Tones (Major)",
    emoji: "④",
    category: "melody",
    shortDescription: "Cante 4+ notas em tom maior.",
    longDescription: "More Tones (Major): frases melódicas longas (4-8 notas) pra cantar de volta.",
    skills: ["Long melodic memory", "Singing", "Major key"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "more-tones-minor",
    name: "More Tones (Minor)",
    emoji: "④",
    category: "melody",
    shortDescription: "Cante 4+ notas em tom menor.",
    longDescription: "More Tones (Minor): frases melódicas longas em tom menor.",
    skills: ["Long melodic memory", "Singing", "Minor key"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "flash-notation-intervals",
    name: "Flash Notation (Intervals)",
    emoji: "📋",
    category: "melody",
    shortDescription: "Leia intervalos na pauta.",
    longDescription: "Flash Notation (Intervals): veja 2 notas na pauta e identifique o intervalo.",
    skills: ["Sight reading", "Intervals", "Notation"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "parrot-phrases",
    name: "Parrot Phrases",
    emoji: "🦜",
    category: "melody",
    shortDescription: "Repita frases melódicas (papagaio).",
    longDescription: "Parrot Phrases: ouça uma frase melódica e cante de volta. Igual ao Vocal Match mas focado em frases completas.",
    skills: ["Melodic memory", "Singing", "Phrase repetition"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },
  {
    id: "vocal-steps-repeat",
    name: "Vocal Steps (Repeat)",
    emoji: "👣",
    category: "melody",
    shortDescription: "Cante escadas melódicas em passos.",
    longDescription: "Vocal Steps (Repeat): sight-singing com frases em movimento de passos (notas adjacentes).",
    skills: ["Sight singing", "Step movement", "Scale internalization"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-pink-500 to-rose-600",
    levels: 20,
  },

  // ═══════════════════════════════════════════════════
  // HARMONY (16 jogos)
  // ═══════════════════════════════════════════════════
  {
    id: "chord-drops",
    name: "Chord Drops",
    emoji: "🎹",
    category: "harmony",
    shortDescription: "Identifique tipos de acordes que caem.",
    longDescription: "Chord Drops: acordes caem como gotas. Ouça e identifique o tipo (maior, menor, dim, aug, 7).",
    skills: ["Chord ID", "Quality recognition"],
    uses_mic: false,
    mechanic: "falling-objects",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "flash-chords",
    name: "Flash Chords",
    emoji: "💡",
    category: "harmony",
    shortDescription: "Identifique acordes rapidamente.",
    longDescription: "Flash Chords: ouça um acorde e identifique entre 4 opções. Vários tipos: maior, menor, dim, aug, sus.",
    skills: ["Chord ID", "Quick recognition"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "tone-trees",
    name: "Tone Trees",
    emoji: "🌳",
    category: "harmony",
    shortDescription: "Encontre as notas que formam um acorde.",
    longDescription: "Tone Trees: ouça um acorde e identifique as notas individuais que o compõem.",
    skills: ["Chord spelling", "Note ID", "Chord structure"],
    uses_mic: false,
    mechanic: "puzzle",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "phrase-fitter",
    name: "Phrase Fitter",
    emoji: "🧩",
    category: "harmony",
    shortDescription: "Conecte arpejos com seus acordes.",
    longDescription: "Phrase Fitter: conecte arpejos maiores/menores com os acordes correspondentes.",
    skills: ["Arpeggios", "Chord-arpeggio link"],
    uses_mic: false,
    mechanic: "puzzle",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "speed-chords",
    name: "Speed Chords",
    emoji: "⚡",
    category: "harmony",
    shortDescription: "Determine qualidade e inversão rápido.",
    longDescription: "Speed Chords: ouça um acorde e identifique qualidade + inversão. Cronometrado.",
    skills: ["Chord quality", "Inversions", "Speed"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "flash-chords-quality",
    name: "Flash Chords (Quality)",
    emoji: "💎",
    category: "harmony",
    shortDescription: "Identifique a qualidade do acorde.",
    longDescription: "Flash Chords (Quality): foque em distinguir maior/menor/dim/aug/sus rapidamente.",
    skills: ["Chord quality", "Quick ID"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "flash-notation-chords",
    name: "Flash Notation (Chords)",
    emoji: "📋",
    category: "harmony",
    shortDescription: "Leia acordes na pauta.",
    longDescription: "Flash Notation (Chords): veja um acorde na pauta e identifique seu nome/tipo.",
    skills: ["Sight reading", "Chord notation"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "chord-spells",
    name: "Chord Spells",
    emoji: "🔤",
    category: "harmony",
    shortDescription: "Soele acordes: nomeie as notas.",
    longDescription: "Chord Spells: dado um nome de acorde (ex: Cmaj7), soele as notas que o compõem (C-E-G-B).",
    skills: ["Chord spelling", "Note names", "Theory"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "chord-locks",
    name: "Chord Locks",
    emoji: "🔐",
    category: "harmony",
    shortDescription: "Determine função, qualidade e inversão.",
    longDescription: "Chord Locks: dado um acorde numa tonalidade, identifique função (I, IV, V), qualidade e inversão.",
    skills: ["Chord function", "Roman numerals", "Inversions"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "speaker-chords",
    name: "Speaker Chords",
    emoji: "🔊",
    category: "harmony",
    shortDescription: "Identifique padrões de progressões comuns.",
    longDescription: "Speaker Chords: ouça uma progressão e identifique o padrão (I-V-vi-IV, I-IV-V, etc).",
    skills: ["Progressions", "Pattern ID", "Common patterns"],
    uses_mic: false,
    mechanic: "multiple-choice",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "flash-progressions-major",
    name: "Flash Progressions (Major)",
    emoji: "📈",
    category: "harmony",
    shortDescription: "Identifique progressões em tom maior.",
    longDescription: "Flash Progressions (Major): ouça uma progressão e identifique os graus (I-IV-V-I, etc).",
    skills: ["Progressions", "Major key", "Roman numerals"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "flash-progressions-minor",
    name: "Flash Progressions (Minor)",
    emoji: "📉",
    category: "harmony",
    shortDescription: "Identifique progressões em tom menor.",
    longDescription: "Flash Progressions (Minor): igual ao Major mas em tom menor.",
    skills: ["Progressions", "Minor key", "Roman numerals"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "flash-cadences",
    name: "Flash Cadences",
    emoji: "🔚",
    category: "harmony",
    shortDescription: "Identifique tipos de cadências.",
    longDescription: "Flash Cadences: ouça um final de frase e identifique o tipo de cadência (perfeita, plagal, decepcionante, etc).",
    skills: ["Cadences", "Phrase endings", "Harmonic resolution"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "triads",
    name: "Triads",
    emoji: "🔺",
    category: "harmony",
    shortDescription: "Identifique tríades (maior, menor, dim, aug).",
    longDescription: "Triads: foque em distinguir os 4 tipos de tríades de 3 notas.",
    skills: ["Triads", "Chord quality", "3-note chords"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "seventh-chords",
    name: "Seventh Chords",
    emoji: "7️⃣",
    category: "harmony",
    shortDescription: "Identifique acordes de sétima.",
    longDescription: "Seventh Chords: distinga maj7, dom7, m7, m7b5, dim7, mMaj7.",
    skills: ["7th chords", "Jazz harmony", "Extended chords"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "inversions",
    name: "Inversions",
    emoji: "🔄",
    category: "harmony",
    shortDescription: "Identifique inversões de acordes.",
    longDescription: "Inversions: dado um acorde, identifique se está na fundamental, 1ª, 2ª ou 3ª inversão.",
    skills: ["Inversions", "Bass note", "Chord voicing"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "arpeggios",
    name: "Arpeggios",
    emoji: "🎻",
    category: "harmony",
    shortDescription: "Identifique arpejos (acordes quebrados).",
    longDescription: "Arpeggios: ouça um arpejo (acorde tocado nota por nota) e identifique o acorde correspondente.",
    skills: ["Arpeggios", "Broken chords", "Melodic-harmonic link"],
    uses_mic: false,
    mechanic: "flashcard",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
  {
    id: "harmony-singing",
    name: "Harmony Singing",
    emoji: "🎶",
    category: "harmony",
    shortDescription: "Cante harmonias (3ª, 5ª) sobre acorde.",
    longDescription: "Harmony Singing: ouça um acorde de fundo e cante a harmonia solicitada (terça, quinta, oitava acima/abaixo).",
    skills: ["Harmony singing", "Interval singing", "Pitch independence"],
    uses_mic: true,
    mechanic: "singing",
    accent: "from-amber-500 to-orange-600",
    levels: 20,
  },
];

/** Mapa id → GameDef pra lookup rápido */
export const GAMES_MAP: Record<string, GameDef> = GAMES.reduce((acc, g) => {
  acc[g.id] = g;
  return acc;
}, {} as Record<string, GameDef>);

/** Total de jogos por categoria */
export const GAMES_BY_CATEGORY: Record<GameCategory, GameDef[]> = {
  sound: GAMES.filter((g) => g.category === "sound"),
  pitch: GAMES.filter((g) => g.category === "pitch"),
  rhythm: GAMES.filter((g) => g.category === "rhythm"),
  tonality: GAMES.filter((g) => g.category === "tonality"),
  melody: GAMES.filter((g) => g.category === "melody"),
  harmony: GAMES.filter((g) => g.category === "harmony"),
};
